Make chocolate
Laboratoria/gym pull request #290
Opened 2022-08-24 17:02 UTC by ssinuco

Ejercicio de dificultad intermediate para ser usado en las sesiones 2 a 5, se resuleve con condicionales, ideal para estudiantes que estan en los proyectos card validation o cipher

2022-09-08 02:44 UTC, reloadercf commented
@ssinuco  seria bueno incluir el este PR el update del readme  de la sesión donde esta pensado usarse este ejercicio.

2022-09-28 20:01 UTC, ssinuco commented
> @ssinuco seria bueno incluir el este PR el update del readme de la sesión donde esta pensado usarse este ejercicio.

Agregado a la sesion 4

2023-01-10 22:22 UTC, reloadercf requested changes
El #290 incluye archivos que se repiten en el otro PR #289

2023-01-10 22:22 UTC, reloadercf commented on exercises/blackjack/README.md
> +---
Este archivo es el mismo que se incluye en el PR #289 
https://github.com/Laboratoria/gym/pull/289/files

2023-01-10 22:22 UTC, reloadercf commented on exercises/blackjack/README.pt-BR.md
> +---
Lo mismo con este archivo ya esta en el otro PR #289

2023-01-10 23:33 UTC, ssinuco commented
> El #290 incluye archivos que se repiten en el otro PR #289

@reloadercf corregida la duplicacion!

2023-01-11 16:14 UTC, reloadercf approved these changes
LGTM

2023-01-11 16:14 UTC, merged