exercise findPairForSum
Laboratoria/gym pull request #293
Opened 2022-09-02 20:30 UTC by MarciaMillanao

# Guia de contribución

## ¿Cómo contribuir con un nuevo ejercicio?

Crear una entrada para el reto dentro de la [carpeta de retos](https://github.com/Laboratoria/gym/tree/main/exercises).

  Esto incluye un README con 4 cosas:
    1. el link al origen del reto
    2. la traduccion del enunciado
    3. los OAs asociados
    4. una carpeta solutions con un archivo para cada solucion propuesta al reto

2022-09-08 02:45 UTC, reloadercf commented
@MarciaMillanao  ¿Para dónde esta pensado ejecutarse este archivo??

2022-09-26 18:46 UTC, MarciaMillanao commented
Agrego recomendación para entrevistadora

2022-09-26 18:53 UTC, MarciaMillanao commented
@reloadercf podemos utilizarlo entre la sesión 6 y 9, también como pósible ejercicio para las sesiones de mock

2023-01-10 22:40 UTC, reloadercf requested changes
@MarciaMillanao esta cool el ejercicio, hace falta agregar 2 cosas para aprobar...

1) proponer mediante un PR una solución ya sea imperativa o declarativa (lo ideal es que sean las 2 soluciones) en el repo https://github.com/Laboratoria/gym-solutions
 
2) Propón la integración a la sesión que consideres deba estar, si bien puede ser  la 6 o la 9, si no la especificamos probablemente no nos aseguremos de usarla :) y que mejor lugar para proponer la sesión donde será usada que este mismo PR #293

2023-01-10 22:40 UTC, reloadercf commented on docs/interviews/first-tech-mock-interview/README-Interviewer.md
> +  mientras está desarrollando el ejercicio recordar que somos entrevistadoras,
👍🏻 +1 I agree

2023-06-27 23:37 UTC, merged